# Configurations for Custom RL Environment

environment:
  name: "VertifarmEnv-v0"
  max_episode_length: 100
  observation_space:
    low: -3
    high: 3
    shape: [33]
  action_space:
    type: "discrete"
    low: -1.0
    high: 1.0
    shape: [12]

rewards:
  success: 10.0
  failure: -10.0
  step_penalty: -0.01

simulation:
  random_seed: 42
  initial_state_range:
    low: -0.5
    high: 0.5

logging:
  log_level: "INFO"
  save_interval: 10
