name: rl_mine_mbrl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi-bindings=21.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - defusedxml=0.7.1
  - entrypoints=0.4
  - idna=3.4
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - jinja2=3.1.3
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=1.13.5
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - nb_conda_kernels=2.3.1
  - nbclassic=1.0.0
  - nbconvert=7.16.3
  - nbconvert-core=7.16.3
  - nbconvert-pandoc=7.16.3
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=23.2
  - pandoc=2.12
  - parso=0.8.3
  - pip=23.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pyyaml=6.0.1
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - testpath=0.6.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.3.3
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - ale-py==0.8.1
      - alembic==1.13.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-generator==1.10
      - async-lru==2.0.4
      - atari-py==0.2.9
      - attrs==23.2.0
      - autobahn==21.3.1
      - automat==22.10.0
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - box2d-py==2.3.5
      - catkin-pkg==1.0.0
      - certipy==0.1.3
      - cloudpickle==1.6.0
      - comm==0.2.2
      - constantly==23.10.4
      - contourpy==1.2.0
      - cython==0.29.37
      - debugpy==1.8.1
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - easydict==1.13
      - etils==1.8.0
      - executing==2.0.1
      - farama-notifications==0.0.4
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - flappy-bird-gymnasium==0.2.2
      - flatbuffers==24.3.25
      - fonttools==4.50.0
      - fqdn==1.5.1
      - fsspec==2024.3.1
      - future==1.0.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.42
      - glfw==2.7.0
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.62.1
      - gym-notices==0.0.8
      - gymnasium==1.0.0a2
      - gymnasium-robotics==1.2.4
      - h5py==3.10.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - hyperlink==21.0.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.4.0
      - incremental==22.10.0
      - ipykernel==6.29.4
      - ipython==8.22.2
      - isoduration==20.11.0
      - jax==0.4.25
      - jax-jumpy==1.0.0
      - jaxlib==0.4.25
      - jedi==0.19.1
      - joblib==1.3.2
      - json5==0.9.24
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyter-telemetry==0.1.0
      - jupyterhub==4.1.0
      - jupyterlab==4.1.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - keras==3.1.1
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - lockfile==0.12.2
      - lz4==4.3.3
      - mako==1.3.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - moviepy==1.0.3
      - mujoco==2.3.7
      - mujoco-py==2.1.2.14
      - namex==0.0.7
      - nbclient==0.10.0
      - nbformat==5.10.3
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.11.0
      - overrides==7.7.0
      - pamela==1.1.0
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - pettingzoo==1.24.3
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.0
      - proglog==0.1.10
      - prometheus-client==0.20.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygame==2.1.3
      - pyglet==1.2.4
      - pygments==2.17.2
      - pyopengl==3.1.7
      - pyopenssl==24.1.0
      - python-ffmpeg-video-streaming==0.1.15
      - pyzmq==25.1.2
      - referencing==0.34.0
      - rich==13.7.1
      - roslibpy==1.6.0
      - rpds-py==0.18.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.2
      - service-identity==24.1.0
      - setproctitle==1.3.3
      - shimmy==1.3.0
      - sklearn==0.0
      - smmap==5.0.1
      - sqlalchemy==2.0.28
      - stable-baselines==2.10.2
      - stable-baselines3==2.3.2
      - stack-data==0.6.3
      - swig==4.2.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - torch==2.2.1
      - tqdm==4.66.2
      - traitlets==5.14.2
      - triton==2.2.0
      - twisted==24.3.0
      - txaio==23.1.1
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - wandb==0.16.5
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - zipp==3.18.1
      - zope-interface==6.2
